from __future__ import annotations

from typing import Any

from pipeline.reconcile.stage_runtime import (
    ReconcileAssemblyDeps,
    ReconcileBindingDeps,
    ReconcileLoaderDeps,
    ReconcileRuntimeDeps,
)


def make_reconcile_loader_deps(
    *,
    run_paper_pipeline_impl: Any,
    extract_layout: Any,
    load_external_layout: Any,
    merge_native_and_external_layout: Any,
    load_external_math: Any,
    external_math_by_page: Any,
    load_mathpix_layout: Any,
    extract_figures: Any,
    pdftotext_available: Any,
    repair_record_text_with_pdftotext: Any,
    extract_pdftotext_pages: Any,
    page_height_map: Any,
) -> ReconcileLoaderDeps:
    return ReconcileLoaderDeps(
        run_paper_pipeline_impl=run_paper_pipeline_impl,
        extract_layout=extract_layout,
        load_external_layout=load_external_layout,
        merge_native_and_external_layout=merge_native_and_external_layout,
        load_external_math=load_external_math,
        external_math_by_page=external_math_by_page,
        load_mathpix_layout=load_mathpix_layout,
        extract_figures=extract_figures,
        pdftotext_available=pdftotext_available,
        repair_record_text_with_pdftotext=repair_record_text_with_pdftotext,
        extract_pdftotext_pages=extract_pdftotext_pages,
        page_height_map=page_height_map,
    )


def make_reconcile_binding_text_deps(
    *,
    normalize_prose_text_impl: Any,
    normalize_reference_text_impl: Any,
    normalize_paragraph_text_impl: Any,
    normalize_figure_caption_text_impl: Any,
    strip_known_running_header_text: Any,
    clean_text: Any,
    block_source_spans: Any,
    default_review: Any,
    make_reference_entry_impl: Any,
    leading_negationslash_artifact_re: Any,
    leading_ocr_marker_re: Any,
    leading_punct_artifact_re: Any,
    leading_var_artifact_re: Any,
    trailing_numeric_artifact_re: Any,
) -> dict[str, Any]:
    return {
        "normalize_prose_text_impl": normalize_prose_text_impl,
        "normalize_reference_text_impl": normalize_reference_text_impl,
        "normalize_paragraph_text_impl": normalize_paragraph_text_impl,
        "normalize_figure_caption_text_impl": normalize_figure_caption_text_impl,
        "strip_known_running_header_text": strip_known_running_header_text,
        "clean_text": clean_text,
        "block_source_spans": block_source_spans,
        "default_review": default_review,
        "make_reference_entry_impl": make_reference_entry_impl,
        "leading_negationslash_artifact_re": leading_negationslash_artifact_re,
        "leading_ocr_marker_re": leading_ocr_marker_re,
        "leading_punct_artifact_re": leading_punct_artifact_re,
        "leading_var_artifact_re": leading_var_artifact_re,
        "trailing_numeric_artifact_re": trailing_numeric_artifact_re,
    }


def make_reconcile_binding_math_deps(
    *,
    math_entry_looks_like_prose_impl: Any,
    should_demote_prose_math_entry_to_paragraph_impl: Any,
    should_demote_graphic_math_entry_to_paragraph_impl: Any,
    should_drop_display_math_artifact_impl: Any,
    group_entry_items_are_graphic_only: Any,
    math_entry_semantic_policy: Any,
    math_entry_category: Any,
    looks_like_prose_paragraph: Any,
    looks_like_prose_math_fragment: Any,
    word_count: Any,
    strong_operator_count: Any,
    mathish_ratio: Any,
    paragraph_block_from_graphic_math_entry_impl: Any,
    split_inline_math: Any,
    repair_symbolic_ocr_spans: Any,
    extract_general_inline_math_spans: Any,
    merge_inline_math_relation_suffixes: Any,
    normalize_inline_math_spans: Any,
) -> dict[str, Any]:
    return {
        "math_entry_looks_like_prose_impl": math_entry_looks_like_prose_impl,
        "should_demote_prose_math_entry_to_paragraph_impl": should_demote_prose_math_entry_to_paragraph_impl,
        "should_demote_graphic_math_entry_to_paragraph_impl": should_demote_graphic_math_entry_to_paragraph_impl,
        "should_drop_display_math_artifact_impl": should_drop_display_math_artifact_impl,
        "group_entry_items_are_graphic_only": group_entry_items_are_graphic_only,
        "math_entry_semantic_policy": math_entry_semantic_policy,
        "math_entry_category": math_entry_category,
        "looks_like_prose_paragraph": looks_like_prose_paragraph,
        "looks_like_prose_math_fragment": looks_like_prose_math_fragment,
        "word_count": word_count,
        "strong_operator_count": strong_operator_count,
        "mathish_ratio": mathish_ratio,
        "paragraph_block_from_graphic_math_entry_impl": paragraph_block_from_graphic_math_entry_impl,
        "split_inline_math": split_inline_math,
        "repair_symbolic_ocr_spans": repair_symbolic_ocr_spans,
        "extract_general_inline_math_spans": extract_general_inline_math_spans,
        "merge_inline_math_relation_suffixes": merge_inline_math_relation_suffixes,
        "normalize_inline_math_spans": normalize_inline_math_spans,
    }


def make_reconcile_binding_front_matter_deps(
    *,
    build_front_matter_impl: Any,
    split_leading_front_matter_records: Any,
    clean_record: Any,
    record_word_count: Any,
    record_width: Any,
    abstract_marker_only_re: Any,
    abstract_lead_re: Any,
    looks_like_front_matter_metadata: Any,
    author_note_re: Any,
    looks_like_affiliation: Any,
    looks_like_intro_marker: Any,
    looks_like_author_line: Any,
    looks_like_contact_name: Any,
    matches_title_line: Any,
    looks_like_affiliation_continuation: Any,
    funding_re: Any,
    dedupe_text_lines: Any,
    filter_front_matter_authors: Any,
    parse_authors: Any,
    parse_authors_from_citation_line: Any,
    normalize_author_line: Any,
    missing_front_matter_author: Any,
    build_affiliations_for_authors: Any,
    missing_front_matter_affiliation: Any,
    strip_author_prefix_from_affiliation_line: Any,
    normalize_title_key: Any,
    clone_record_with_text: Any,
    looks_like_body_section_marker: Any,
    preprint_marker_re: Any,
    keywords_lead_re: Any,
    abstract_text_is_usable: Any,
    normalize_abstract_candidate_text: Any,
    front_matter_missing_placeholder: Any,
    normalize_section_title_impl: Any,
    clean_heading_title: Any,
    parse_heading_label: Any,
    front_block_text_impl: Any,
    recover_missing_front_matter_abstract_impl: Any,
    abstract_quality_flags: Any,
    leading_abstract_text: Any,
    abstract_text_is_recoverable: Any,
    replace_front_matter_abstract_text: Any,
    opening_abstract_candidate_records: Any,
) -> dict[str, Any]:
    return {
        "build_front_matter_impl": build_front_matter_impl,
        "split_leading_front_matter_records": split_leading_front_matter_records,
        "clean_record": clean_record,
        "record_word_count": record_word_count,
        "record_width": record_width,
        "abstract_marker_only_re": abstract_marker_only_re,
        "abstract_lead_re": abstract_lead_re,
        "looks_like_front_matter_metadata": looks_like_front_matter_metadata,
        "author_note_re": author_note_re,
        "looks_like_affiliation": looks_like_affiliation,
        "looks_like_intro_marker": looks_like_intro_marker,
        "looks_like_author_line": looks_like_author_line,
        "looks_like_contact_name": looks_like_contact_name,
        "matches_title_line": matches_title_line,
        "looks_like_affiliation_continuation": looks_like_affiliation_continuation,
        "funding_re": funding_re,
        "dedupe_text_lines": dedupe_text_lines,
        "filter_front_matter_authors": filter_front_matter_authors,
        "parse_authors": parse_authors,
        "parse_authors_from_citation_line": parse_authors_from_citation_line,
        "normalize_author_line": normalize_author_line,
        "missing_front_matter_author": missing_front_matter_author,
        "build_affiliations_for_authors": build_affiliations_for_authors,
        "missing_front_matter_affiliation": missing_front_matter_affiliation,
        "strip_author_prefix_from_affiliation_line": strip_author_prefix_from_affiliation_line,
        "normalize_title_key": normalize_title_key,
        "clone_record_with_text": clone_record_with_text,
        "looks_like_body_section_marker": looks_like_body_section_marker,
        "preprint_marker_re": preprint_marker_re,
        "keywords_lead_re": keywords_lead_re,
        "abstract_text_is_usable": abstract_text_is_usable,
        "normalize_abstract_candidate_text": normalize_abstract_candidate_text,
        "front_matter_missing_placeholder": front_matter_missing_placeholder,
        "normalize_section_title_impl": normalize_section_title_impl,
        "clean_heading_title": clean_heading_title,
        "parse_heading_label": parse_heading_label,
        "front_block_text_impl": front_block_text_impl,
        "recover_missing_front_matter_abstract_impl": recover_missing_front_matter_abstract_impl,
        "abstract_quality_flags": abstract_quality_flags,
        "leading_abstract_text": leading_abstract_text,
        "abstract_text_is_recoverable": abstract_text_is_recoverable,
        "replace_front_matter_abstract_text": replace_front_matter_abstract_text,
        "opening_abstract_candidate_records": opening_abstract_candidate_records,
    }


def make_reconcile_binding_block_builder_deps(
    *,
    build_blocks_for_record_impl: Any,
    record_analysis_text: Any,
    is_short_ocr_fragment: Any,
    caption_label: Any,
    looks_like_real_code_record: Any,
    split_code_lines: Any,
    list_item_marker: Any,
    review_for_math_entry: Any,
    review_for_math_ref_block: Any,
    match_external_math_entry_impl: Any,
    build_block_math_entry: Any,
    normalize_formula_display_text: Any,
    classify_math_block: Any,
    review_for_algorithm_block_text: Any,
    overlapping_external_math_entries_impl: Any,
    trim_embedded_display_math_from_paragraph_impl: Any,
    display_math_prose_cue_re: Any,
    display_math_resume_re: Any,
    display_math_start_re: Any,
    looks_like_display_math_echo_impl: Any,
    short_word_re: Any,
) -> dict[str, Any]:
    return {
        "build_blocks_for_record_impl": build_blocks_for_record_impl,
        "record_analysis_text": record_analysis_text,
        "is_short_ocr_fragment": is_short_ocr_fragment,
        "caption_label": caption_label,
        "looks_like_real_code_record": looks_like_real_code_record,
        "split_code_lines": split_code_lines,
        "list_item_marker": list_item_marker,
        "review_for_math_entry": review_for_math_entry,
        "review_for_math_ref_block": review_for_math_ref_block,
        "match_external_math_entry_impl": match_external_math_entry_impl,
        "build_block_math_entry": build_block_math_entry,
        "normalize_formula_display_text": normalize_formula_display_text,
        "classify_math_block": classify_math_block,
        "review_for_algorithm_block_text": review_for_algorithm_block_text,
        "overlapping_external_math_entries_impl": overlapping_external_math_entries_impl,
        "trim_embedded_display_math_from_paragraph_impl": trim_embedded_display_math_from_paragraph_impl,
        "display_math_prose_cue_re": display_math_prose_cue_re,
        "display_math_resume_re": display_math_resume_re,
        "display_math_start_re": display_math_start_re,
        "looks_like_display_math_echo_impl": looks_like_display_math_echo_impl,
        "short_word_re": short_word_re,
    }


def make_reconcile_binding_layout_heading_deps(
    *,
    merge_layout_and_figure_records_impl: Any,
    layout_record: Any,
    absorb_figure_caption_continuations: Any,
    figure_label_token: Any,
    synthetic_caption_record: Any,
    inject_external_math_records: Any,
    mark_records_with_external_math_overlap_impl: Any,
    repair_record_text_with_mathpix_hints_impl: Any,
    mathpix_text_blocks_by_page: Any,
    mathpix_text_hint_candidate: Any,
    is_mathpix_text_hint_better: Any,
    mathpix_prose_lead_repair_candidate: Any,
    promote_heading_like_records_impl: Any,
    looks_like_bad_heading: Any,
    collapse_ocr_split_caps: Any,
    decode_control_heading_label: Any,
    normalize_decoded_heading_title: Any,
    split_embedded_heading_paragraph: Any,
) -> dict[str, Any]:
    return {
        "merge_layout_and_figure_records_impl": merge_layout_and_figure_records_impl,
        "layout_record": layout_record,
        "absorb_figure_caption_continuations": absorb_figure_caption_continuations,
        "figure_label_token": figure_label_token,
        "synthetic_caption_record": synthetic_caption_record,
        "inject_external_math_records": inject_external_math_records,
        "mark_records_with_external_math_overlap_impl": mark_records_with_external_math_overlap_impl,
        "repair_record_text_with_mathpix_hints_impl": repair_record_text_with_mathpix_hints_impl,
        "mathpix_text_blocks_by_page": mathpix_text_blocks_by_page,
        "mathpix_text_hint_candidate": mathpix_text_hint_candidate,
        "is_mathpix_text_hint_better": is_mathpix_text_hint_better,
        "mathpix_prose_lead_repair_candidate": mathpix_prose_lead_repair_candidate,
        "promote_heading_like_records_impl": promote_heading_like_records_impl,
        "looks_like_bad_heading": looks_like_bad_heading,
        "collapse_ocr_split_caps": collapse_ocr_split_caps,
        "decode_control_heading_label": decode_control_heading_label,
        "normalize_decoded_heading_title": normalize_decoded_heading_title,
        "split_embedded_heading_paragraph": split_embedded_heading_paragraph,
    }


def make_reconcile_binding_deps(
    *,
    text_deps: dict[str, Any],
    math_deps: dict[str, Any],
    front_matter_deps: dict[str, Any],
    block_builder_deps: dict[str, Any],
    layout_heading_deps: dict[str, Any],
) -> ReconcileBindingDeps:
    return ReconcileBindingDeps(
        **text_deps,
        **math_deps,
        **front_matter_deps,
        **block_builder_deps,
        **layout_heading_deps,
    )


def make_reconcile_assembly_deps(
    *,
    merge_math_fragment_records: Any,
    page_one_front_matter_records: Any,
    is_title_page_metadata_record: Any,
    build_section_tree: Any,
    attach_orphan_numbered_roots: Any,
    split_late_prelude_for_missing_intro: Any,
    build_abstract_decision: Any,
    should_replace_front_matter_abstract: Any,
    section_node_type: Any,
    prepare_section_nodes: Any,
    split_trailing_reference_records: Any,
    extract_reference_records_from_tail_section: Any,
    reference_records_from_mathpix_layout: Any,
    materialize_sections: Any,
    section_id_impl: Any,
    merge_reference_records: Any,
    is_figure_debris: Any,
    looks_like_running_header_record: Any,
    looks_like_table_body_debris: Any,
    suppress_embedded_table_headings: Any,
    should_merge_paragraph_records: Any,
    table_caption_re: Any,
    merge_code_records_impl: Any,
    merge_paragraph_records_impl: Any,
    compile_formulas: Any,
    annotate_formula_classifications: Any,
    annotate_formula_semantic_expr: Any,
    suppress_graphic_display_math_blocks_impl: Any,
    suppress_running_header_blocks_impl: Any,
    compact_text: Any,
    running_header_text_re: Any,
    normalize_footnote_blocks_impl: Any,
    starts_like_sentence: Any,
    merge_paragraph_blocks_impl: Any,
    now_iso: Any,
    build_canonical_document: Any,
) -> ReconcileAssemblyDeps:
    return ReconcileAssemblyDeps(
        merge_math_fragment_records=merge_math_fragment_records,
        page_one_front_matter_records=page_one_front_matter_records,
        is_title_page_metadata_record=is_title_page_metadata_record,
        build_section_tree=build_section_tree,
        attach_orphan_numbered_roots=attach_orphan_numbered_roots,
        split_late_prelude_for_missing_intro=split_late_prelude_for_missing_intro,
        build_abstract_decision=build_abstract_decision,
        should_replace_front_matter_abstract=should_replace_front_matter_abstract,
        section_node_type=section_node_type,
        prepare_section_nodes=prepare_section_nodes,
        split_trailing_reference_records=split_trailing_reference_records,
        extract_reference_records_from_tail_section=extract_reference_records_from_tail_section,
        reference_records_from_mathpix_layout=reference_records_from_mathpix_layout,
        materialize_sections=materialize_sections,
        section_id_impl=section_id_impl,
        merge_reference_records=merge_reference_records,
        is_figure_debris=is_figure_debris,
        looks_like_running_header_record=looks_like_running_header_record,
        looks_like_table_body_debris=looks_like_table_body_debris,
        suppress_embedded_table_headings=suppress_embedded_table_headings,
        should_merge_paragraph_records=should_merge_paragraph_records,
        table_caption_re=table_caption_re,
        merge_code_records_impl=merge_code_records_impl,
        merge_paragraph_records_impl=merge_paragraph_records_impl,
        compile_formulas=compile_formulas,
        annotate_formula_classifications=annotate_formula_classifications,
        annotate_formula_semantic_expr=annotate_formula_semantic_expr,
        suppress_graphic_display_math_blocks_impl=suppress_graphic_display_math_blocks_impl,
        suppress_running_header_blocks_impl=suppress_running_header_blocks_impl,
        compact_text=compact_text,
        running_header_text_re=running_header_text_re,
        normalize_footnote_blocks_impl=normalize_footnote_blocks_impl,
        starts_like_sentence=starts_like_sentence,
        merge_paragraph_blocks_impl=merge_paragraph_blocks_impl,
        now_iso=now_iso,
        build_canonical_document=build_canonical_document,
    )


def make_reconcile_runtime_deps(
    *,
    loaders: ReconcileLoaderDeps,
    bindings: ReconcileBindingDeps,
    assembly: ReconcileAssemblyDeps,
) -> ReconcileRuntimeDeps:
    return ReconcileRuntimeDeps(
        loaders=loaders,
        bindings=bindings,
        assembly=assembly,
    )
