from __future__ import annotations

from pipeline.reconcile.section_filters import (
    ends_like_clause_lead_in,
    ends_like_short_lead_in,
    is_paragraph_like_record,
    looks_like_running_header_record,
    looks_like_same_page_column_continuation,
    looks_like_table_body_debris,
    make_ends_like_clause_lead_in,
    make_ends_like_short_lead_in,
    make_looks_like_running_header_record,
    make_looks_like_table_body_debris,
    make_merge_anchor_spans,
    make_should_merge_paragraph_records,
    make_starts_like_paragraph_continuation,
    make_starts_like_strong_paragraph_continuation,
    make_suppress_embedded_table_headings,
    merge_anchor_spans,
    should_merge_paragraph_records,
    starts_like_paragraph_continuation,
    starts_like_sentence,
    starts_like_strong_paragraph_continuation,
    suppress_embedded_table_headings,
)


__all__ = [
    "ends_like_clause_lead_in",
    "ends_like_short_lead_in",
    "is_paragraph_like_record",
    "looks_like_running_header_record",
    "looks_like_same_page_column_continuation",
    "looks_like_table_body_debris",
    "make_ends_like_clause_lead_in",
    "make_ends_like_short_lead_in",
    "make_looks_like_running_header_record",
    "make_looks_like_table_body_debris",
    "make_merge_anchor_spans",
    "make_should_merge_paragraph_records",
    "make_starts_like_paragraph_continuation",
    "make_starts_like_strong_paragraph_continuation",
    "make_suppress_embedded_table_headings",
    "merge_anchor_spans",
    "should_merge_paragraph_records",
    "starts_like_paragraph_continuation",
    "starts_like_sentence",
    "starts_like_strong_paragraph_continuation",
    "suppress_embedded_table_headings",
]
